# cache for public repo on container-based infrastructure see:
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
# http://docs.travis-ci.com/user/caching
#
sudo: false
language: java
jdk:
  - openjdk8
  - openjdk11
install: "travis_retry mvn install -Pintegration-tests -DskipTests=true -B -V -C -q"
script: "travis_retry mvn verify -Pintegration-tests -B -V -C -q"
cache:
  directories:
    - $HOME/.m2/repository/
